### ISSUE TITLE
Pressing Esc in mouse input mode kills Termbox

### ISSUE THREAD

**Issue by ferbivore** [ferbivore/luabox#5]
```
panic: unreachable

goroutine 8 [running]:
github.com/nsf/termbox-go.extract_event(0x82040c400, 0x1, 0x40, 0x82053ed48,     0x68400)
        ~/Go/src/github.com/nsf/termbox-go/termbox.go:372     +0x1c0
github.com/nsf/termbox-go.PollEvent(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        ~/Go/src/github.com/nsf/termbox-go/api.go:329 +0x482
main.termbox_listener(0x82040e3c0)
        ~/Go/src/github.com/ferbivore/luabox/api.go:241 +0x1f0
created by main.main
        ~/Go/src/github.com/ferbivore/luabox/main.go:43 +0x388

goroutine 1 [chan receive]:
main.main()
        ~/Go/src/github.com/ferbivore/luabox/main.go:45 +0x3e6

goroutine 5 [syscall]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 6 [select, locked to thread]:
runtime.gopark(0x2bca88, 0x820420728, 0x260a88, 0x6, 0x36318, 0x2)
        /usr/local/go/src/runtime/proc.go:185 +0x169
runtime.selectgoImpl(0x820420728, 0x0, 0x18)
        /usr/local/go/src/runtime/select.go:392 +0xa64
runtime.selectgo(0x820420728)
        /usr/local/go/src/runtime/select.go:212 +0x12
runtime.ensureSigM.func1()
        /usr/local/go/src/runtime/signal1_unix.go:190 +0x326
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 7 [runnable]:
github.com/nsf/termbox-go.Init.func1()
        ~/Go/src/github.com/nsf/termbox-go/api.go:96 +0x303
created by github.com/nsf/termbox-go.Init
        ~/Go/src/github.com/nsf/termbox-go/api.go:106 +0x8b9

goroutine 9 [chan receive]:
main.mainloop(0x7fff5fbff922, 0xa, 0x82040e3c0)
        ~/Go/src/github.com/ferbivore/luabox/loop.go:52 +0xaf9
created by main.main
        ~/Go/src/github.com/ferbivore/luabox/main.go:44 +0x3c1
```

**Comment by ferbivore** [comment]
Run this (after cloning and doing `go build`, of course) and hit Esc for a demonstration:

```
./luabox examples/issue5.lua 2> error.log; reset; cat error.log
```

**Comment by ferbivore** [comment]
https://github.com/nsf/termbox-go/issues/97

**Comment by ferbivore** [comment]
> `termbox.InputMouse` is not a valid input mode. It must be one of the InputEsc or InputAlt and optionally InputMouse. Patch will force setting it to Esc if you don't provide on of esc or alt.

Replaced `termbox.inmode.mouse` with `escMouse` and `altMouse`.
